[package]
name = "stivale"
version = "0.1.0"
authors = ["Martin LÃ¶ffler <git@fatalerrorcoded.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
